### ISSUE TITLE
Add Firstname to Database

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/backend-server#124]
## Idea

Right now, we have a username property in the database and from that, we are extrapolating the user's first and last name. The only problem with that is that my last name is McGonagle- if it wasn't, this problem wouldn't exist. The trouble comes with the first 'G' in the name. Since the computer doesn't know all of the last names in the world, it couldn't possibly know to capitalize that 'G'. And so, we have decided to add first and last names to the database. 

To maximize exposure and for simplicity, I'll add a bunch of issues so that a bunch of people can pick this up. If you want to help with this issue- just leave a comment saying that, and we will mark you as an assignee.

Cheers!

## Todo
- [x] Add a first name to sequelize defintion
- [x] Add first name to all necessary user queries

**Comment by William-McGonagle** [comment]
@MassiGy @NeilChaudhari Sorry to bump this issue, but we should fix this up soon as our settings pages are now under development.

**Comment by MassiGy** [comment]
hey @William-McGonagle,

Thanks for the explanation. I'am currently testing the new version of the API Routes  that I came up with to fix the issue #122.

After finishing it, I will tackle this one right after it.

Massiles.

**Comment by MassiGy** [comment]
Hey @William-McGonagle,

I've been looking around on the controllers to see where the first and last name properties could be used, and I did not found any. Could you please explain why do we need to add those on the database, and how the frontend will use or query them.

**Couple of things to consider**

 I've been a mongoDB developer, but these things still relevant on the SQL land too.

- If you are going to always query the first and the last name just to get the full name,  just store the full name instead ( +Performance ).
- If you need the first and the last name as well as the full name, you can make the full name a virtual property, this means that you do not actually store it on the database, but you can get it from the database server. ( +Performance ).



Hope that these little points will help.

Massiles.
