### ISSUE TITLE
More Duck Item Ideas Needed

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/backend-server#13]
Right now there are a couple of hats and eyes that users can add to their ducks, but we need more options.

If you have any ideas for things you want to be added to the ducks, leave a comment below! 

![Cool Duck](http://fairfield-programming.herokuapp.com/duck/0100000061/20)

**Comment by DiegoPrestesGit** [comment]
Well, I'll give some ideas and you tell me if I'm in the right way:

- new wing formats, nothing crazy but we could do some extra shapes;
- tail, he could have some more tails with nice feathers and ornaments;
- some new hats;
- a robot like duck, like a synth;

I could give some more ideas but I'm not sure if I'm in the right way of thinking, so you can reply me and I might be able to code some ideas with you. S2

**Comment by William-McGonagle** [comment]
I really like the idea of a cyborg duck- so I'm going to add that to the to-do list right now, but I am interested in what new wing formats or tails you would like. I could definitely add those in, I would just need to add a bit to the hex-parser.

**Comment by William-McGonagle** [comment]
I just saw this online- and maybe there could be some cool ideas in here, but I'm not really sure... what do you think?

<img alt="Wings" width="200px" src="https://i.pinimg.com/originals/ab/6b/9c/ab6b9c57bf293b006b41d3c8a4db8e10.jpg">

**Comment by DiegoPrestesGit** [comment]
Oh I see, I surely should be more specific! Those are cool, we have to find a way to fit in the duck. I also saw that you added some issues on new features for the duck, I'll try to do some of those.

**Comment by William-McGonagle** [comment]
Sounds great- thank you so much for the help!
