### ISSUE TITLE
Add in Emailing Functionality

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/backend-server#16]

**Comment by MassiGy** [comment]
Hey @William-McGonagle,

I think I fixed this issue on my recent pull request #110
Please go ahead and check it out !

Thanks in advance !
Massiles.

**Comment by William-McGonagle** [comment]
Hey @MassiGy, 

I checked it out and it all looks good. Thanks for the help!

Thanks,
William McGonagle
