### ISSUE TITLE
Email System

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/backend-server#3]

**Comment by MassiGy** [comment]
I am thinking about creating a node module, that will basically create an mailer for us, which will use the `nodemailer` lib. With this implementation, we can import where ever we want in our backend code, and we can send emails from there.

_What do you think, if you like it, please assign it to me !_

Thanks 
Massiles.

**Comment by MassiGy** [comment]
Well I think my system will close this issue as well !
What do you think @William-McGonagle ?

Thanks in advance !
Massiles.
