### ISSUE TITLE
Add Binoculars as Eye-Option for Ducks

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/backend-server#30]

**Comment by DiegoPrestesGit** [comment]
Added binoculars to the duck eye:

![image](https://user-images.githubusercontent.com/57499868/148155758-b795905e-7ee5-4967-809a-b321601a8d02.png)

you can check it out and change however you like here in my [figma](https://www.figma.com/file/vNFL1i21rLLldBn7jQaKF4/ducks?node-id=0%3A1)

**Comment by William-McGonagle** [comment]
Hey @DiegoPrestesGit, I'm moving these issues over to a new repository, and I will add a rules section for the items so that they have a distinct and consistent style. You can see the new issue [here](https://github.com/fairfield-programming/ducks/issues/1).

**Comment by DiegoPrestesGit** [comment]
Right, it makes sense actually. should I copy paste my duck in the new repo?

**Comment by William-McGonagle** [comment]
Yeah sure- that would be great!

**Comment by DiegoPrestesGit** [comment]
It's there o/
