### ISSUE TITLE
Add Football as Item for Ducks

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/backend-server#33]

**Comment by github4maninder** [comment]
Hi, I would like to work on this request.

**Comment by William-McGonagle** [comment]
hey @github4maninder, I'm moving all of the duck stuff into a repository [here](https://github.com/fairfield-programming/ducks). If you could add your pull request there, it would be great!

**Comment by William-McGonagle** [comment]
The issue is [here](https://github.com/fairfield-programming/ducks/issues/2).
