### ISSUE TITLE
Make Events Owned by Users

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/backend-server#41]
## Idea
Events are great but they should only be deletable by the person that created them, and they should only be able to be edited by the person that created them as well. This will stop spam users from deleting events that users worked hard to build. 

## Todo
- [ ] Add a relationship between events and users where users own multiple events
- [ ] Add auth to all of the events so that only the owner of the event can edit it

**Comment by NeilChaudhari** [comment]
done
