### ISSUE TITLE
Add Fairfield Programming Association to Github Explore Page

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/backend-server#43]
## Idea
Right now, the FPA is a fairly young open-source organization that needs help to grow. To do this, we need to get our name heard, so we need someone who is not yet a contributor to our project to help out by creating a pull request on the 'github/explore' repo. Just add the 'fairfield-programming/fairfield-programming.github.io' to [this file](https://github.com/github/explore/blob/main/collections/open-source-organizations/index.md), and you have helped the FPA immensely. 

This page is for open-source organizations, which the Fairfield Programming Association is, so you would be following all of the correct guidelines by contributing it. 

## Todo
- [ ] Add our website repo to the 'open-source-organizations' Readme file

**Comment by github4maninder** [comment]
hi, i have also updated this info in the existing PR request. Kindly assign this to me. Thanks.

**Comment by William-McGonagle** [comment]
Just assigned you- thanks again!

**Comment by github4maninder** [comment]
issue resolved. 👍🏻

**Comment by William-McGonagle** [comment]
Thank you so much!!!
