### ISSUE TITLE
Add Fairfield Programming Association to Github Explore Page

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/backend-server#44]
## Idea
Right now, the FPA is a fairly young open-source organization that needs help to grow. To do this, we need to get our name heard, so we need someone who is not yet a contributor to our project to help out by creating a pull request on the 'github/explore' repo. Just add the 'fairfield-programming/fairfield-programming.github.io' to [this file](https://github.com/github/explore/blob/main/collections/github-pages-examples/index.md), and you have helped the FPA immensely. 

This file is a list of Github Pages examples, which our repo is. 

## Todo
- [ ] Add our website repo to the 'open-source-organizations' Readme file

**Comment by github4maninder** [comment]
hi, I would love to work on this. kindly assign this request to me.

**Comment by William-McGonagle** [comment]
Okay- thank you!

**Comment by github4maninder** [comment]
Created a pull request now waiting for the merge. I will keep you posted! thanks

**Comment by github4maninder** [comment]
issue resolved. 👍🏻

**Comment by William-McGonagle** [comment]
Wooo woooo!!!!
