### ISSUE TITLE
Add a Friend System

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/backend-server#45]
**Is your feature request related to a problem? Please describe.**
Users want to be able to interact with one another but they are not able to if they cannot friend each other. This system would also let us build a chat system and other features later on.

**Describe the solution you'd like**
We could add in a friend system to the server by using the sequelize relationship system. That would let people friend each other and accept friend requests. 

**Describe alternatives you've considered**
I've considered doing a system like the one that Github and Instagram has where you can follow people and then they can follow you back. I think that this system would be much simpler to implement. 

**Additional context**
I will link some other issues here on what we need to do to accomplish this.

- [x] #49
- [x] #46
- [x] #47
- [x] #48
- [x] #50
- [x] #73

**Comment by MassiGy** [comment]
I think this is now implemented.

Massiles.
