### ISSUE TITLE
Create an Endpoint to Query Followers

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/backend-server#46]
## Idea
_Full Idea Here - #45_

Users need to see who they are followed by, so we are going to add in an endpoint where they can check what users are following them. 

The endpoint will be `/user/:id/followers`

## Todo
- [x] Endpoints
     - [x] Add an endpoint for querying who a user is followed by
- [x] Testing
     - [x] Test the previous endpoint to make sure it works

**Comment by MassiGy** [comment]
This is already implemented.

Massiles.
