### ISSUE TITLE
Create an Endpoint for Blocking a User

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/backend-server#50]
## Idea
_Full Idea Here - #45_

Right now we are working on a friend system, but what would a friend system be without the ability to block users. That is why we need to add an endpoint for blocking users. 

The path of the endpoint would be `/user/:id/block` and the only way to access it would be through a post request. Proper authentication is needed for this endpoint, and if the user is already blocked, the server should tell the client this. 

## Todo
- [x] Endpoints
     - [x] `POST /user/:id/block`
- [x] Testing
     - [x] `POST /user/:id/block`

**Comment by MassiGy** [comment]
This is already in place.

Massiles.
