### ISSUE TITLE
Separate Testing Suite

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/backend-server#53]
## Idea
Right now the project is growing in size at an incredible rate, but the only downside is that the testing suite is just a single file. In most cases, this would work fine, but this monolithic file needs to be cut down and separated into a bunch of separate testing files. We can keep the same file system structure to organize the files but we just need to break up the testing suite. 

## Todo
- [x] #54 
- [x] #55 
- [x] #56 
- [x] #57 
- [x] #58

**Comment by NikitaLejnev** [comment]
@William-McGonagle Reporting for duty, Sir.

**Comment by William-McGonagle** [comment]
Hey, @NikitaLejnev- would you like to join our Organization? It's a non-profit and just starting out so there wouldn't really be any pay, but we would love to have you!

**Comment by NikitaLejnev** [comment]
@William-McGonagle I would love to help out. My programming skill leaves much to be desired but I hope to proove useful.

**Comment by William-McGonagle** [comment]
No- you seem do be doing a great job! I just invited you to the organization if you would like to join up.
