### ISSUE TITLE
Create Testing Suite for Duck Endpoints

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/backend-server#54]
## Idea
Right now all of our testing suites are in one file- `src/tests/test.js` but we want to move each testing suite into its own file. 

For this issue, we need to move the testing suite for duck endpoints into its own file titled `src/tests/duck.js`. If you want to do this, comment on this issue and I will assign you to it. 

## Todo
- [ ] Move the testing functions into their own file

**Comment by NikitaLejnev** [comment]
@William-McGonagle I would like to work on this.

**Comment by William-McGonagle** [comment]
I'll check out your pull request when I get home.
