### ISSUE TITLE
🦆 New Duck Jokes Needed

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/backend-server#66]
We've got a couple of really solid duck jokes but we need some more because I'm getting tired of looking at the same jokes over and over. If you've got any jokes, comment them below and I will add them in. If you like one of the jokes in the comments, make sure to react to it with an emoji!

You can also submit a pull request with the joke in it. This will save me some time and it will make you a contributor to the project!

**Comment by djsiddz** [comment]
Seems to be a duplicate issue of #8 ?

**Comment by William-McGonagle** [comment]
Yep- it is.
