### ISSUE TITLE
Add Documentation to Joke Endpoint

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/backend-server#67]
## Idea
At this point, we have a ton of endpoints and the number just keeps growing. We need to document all of these endpoints but the only way to do that is to write about each of them. That is where you come in. If you would like to document this endpoint, just comment on the post, and I will assign it to you.

## Todo
- [ ] Add an item to the OpenAPI file that shows how to Query the Joke
- [x] Add a documentation page about "Joke" Endpoint

**Comment by fuadop** [comment]
Hey @William-McGonagle , I would love to work on this. Tho I can't find any swagger doc set up in the repo yet.

**Comment by cooltil786** [comment]
> Hey @William-McGonagle , I would love to work on this. Tho I can't find any swagger doc set up in the repo yet.

Hello is there anyway I can get you out from this

**Comment by fuadop** [comment]
@cooltil786 yea, I didn't get any feedback for a while now.

**Comment by William-McGonagle** [comment]
Hey @fuadop and @cooltil786 –

This repository is sadly no longer maintained as we switched away from a Monolithic server architecture. If you would like to work on an FPA project though, we [have many](https://github.com/fairfield-programming). I would recommend checking out either the [OpenList website](https://github.com/fairfield-programming/openlist-website) or the [main website](https://github.com/fairfield-programming/fairfield-programming.github.io), to see what issues could be helped with. 

Cheers!
William McGonagle
