### ISSUE TITLE
[IDEA] Refactor based on SonarQube reports

### ISSUE THREAD

**Issue by NikitaLejnev** [fairfield-programming/backend-server#74]
**Is your feature request related to a problem? Please describe.**
According to SonarQube, the code has 58 code smells. This equates to 6 hours of code debt. The code will become hard to maintain and extend without refactoring.

**Describe the solution you'd like**
I refactor the code and create a pull request.

**Describe alternatives you've considered**
Someone else refactors the code.

**Additional context**
![image](https://user-images.githubusercontent.com/33813313/147645679-c1c9f899-950c-4f80-9d6f-099592527994.png)

**Comment by NikitaLejnev** [comment]
Working on it.
![image](https://user-images.githubusercontent.com/33813313/147656886-43640573-8c85-44dd-8600-0d60dc9a6d11.png)

**Comment by NikitaLejnev** [comment]
28 code smells are commented out lines in tests/editUser.js. I have no idea if I should delete or uncomment them.
1 is a long regexp in the email check.
The rest I won't touch, at least for now.

![image](https://user-images.githubusercontent.com/33813313/147660187-352f4829-c621-434a-880c-dbb2b1b769f2.png)

**Comment by William-McGonagle** [comment]
Thank you so much for doing this- I've never used SonarQube, but I have seen some of the shields on other repositories. What does it do?

**Comment by NikitaLejnev** [comment]
@William-McGonagle It is an open source platform for code inspections. It analyzes the code and reports on bugs, style problems and security hotspots.
