### ISSUE TITLE
[IDEA] Introduce consistent formatting

### ISSUE THREAD

**Issue by NikitaLejnev** [fairfield-programming/backend-server#76]
**Is your feature request related to a problem? Please describe.**
Code style is inconsistent across the code base. This drastically reduces the readability and, therefore, maintainability.

**Describe the solution you'd like**
Lint with Prettifier. 

**Describe alternatives you've considered**
We can also use ESLint or any other solution. Either way I am eager to work on this.

**Comment by William-McGonagle** [comment]
This sounds like a great idea- I'm going to look into doing this using our CI/CD pipeline so that it's all automated.
