### ISSUE TITLE
Make Joke Endpoints Use Utilities Library

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/backend-server#79]
Right now, we have a great utilities folder thanks to @NikitaLejnev, but not all of our endpoints are using it. We should change the joke endpoints so that they use this excellent library.

If you are already a contributor to the project, leave this for someone who hasn't contributed yet. 

And if you want to do this, drop a comment on this issue, and I will assign it to you. 

Cheers!

**Comment by Nokkvi** [comment]
I would be happy to help, can I take this issue?

**Comment by William-McGonagle** [comment]
Yeah- sure!

**Comment by Nokkvi** [comment]
Created pull request #86

**Comment by William-McGonagle** [comment]
Merged the pull request- Thank you!
