### ISSUE TITLE
Make Event Endpoints Utilize the Utility Library

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/backend-server#80]
# Idea
We just got a brand new utility library for express, courtesy of @NikitaLejnev. But the only problem is that we haven't implemented it in our entire codebase. If you want to implement it, just drop a comment and I'll assign you to the issue. 

If your already a contributor, ignore this issue as it's to encourage new contributors.

## Todo
- [ ] Add Utility Code into Events Endpoint 

Cheers!

**Comment by malikmukhtar** [comment]
Hello @William-McGonagle , I'd love to work on this. thanks

**Comment by NeilChaudhari** [comment]
sounds good!

**Comment by malikmukhtar** [comment]
@NeilChaudhari  @William-McGonagle Can you please point me to the utility library you referring to because the eventsUtils.js in the /library folder has been applied to the event endpoint

**Comment by MassiGy** [comment]
Indeed it is. This should be closed then.

Massiles.
