### ISSUE TITLE
Easy: 🤪 Create Documentation Website using Github Pages 

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/backend-server#84]
## Idea
We have a huge codebase at this point and it keeps on growing in size. So, what do we need to do? Add more documentation. If we do this, we will enable new contributors to add code to the project, and we can keep growing. 

If you want to do this, leave a comment, and I will assign you to the issue!

Cheers!

## Todo
- [ ] Setup a Build System for Documentation using Github Pages

**Comment by Nokkvi** [comment]
@William-McGonagle , I could take a stab at this.

**Comment by William-McGonagle** [comment]
Sure- sounds good! When you're done setting it up, I can make it live using the domain.

**Comment by William-McGonagle** [comment]
Also, @Nokkvi Do you want to join our organization? We would love to have you.

**Comment by Nokkvi** [comment]
Sure, I'll join. One question I have regarding this issue. How does using something like [mkdocs-material](https://squidfunk.github.io/mkdocs-material/) sound? It would provide navigation, themes(with light/dark setting) and table of contents for each page.

**Comment by William-McGonagle** [comment]
I just checked it out, and it seems great! I'll also invite you to the Github organization.

**Comment by William-McGonagle** [comment]
@Nokkvi Maybe we would be better off if I made a separate repository for the documentation- how does that sound?

**Comment by Nokkvi** [comment]
@William-McGonagle If the documentation will be covering multiple projects then I think that's the way to go.

**Comment by William-McGonagle** [comment]
Sounds good- I'll make the repository right now and deploy it to GitHub pages.

**Comment by William-McGonagle** [comment]
Okay, the repository is [here](https://github.com/fairfield-programming/docs). 

And the website is [here](https://docs.fairfieldprogramming.org/).
