### ISSUE TITLE
Reduce code duplication

### ISSUE THREAD

**Issue by NikitaLejnev** [fairfield-programming/backend-server#87]
## Idea
I think it is incredibly difficult to grow the codebase. Refactoring is very frustrating because the same steps need to be applied for several files. We are going to experience maintenance Hell if we won't at least keep the duplication at the current level.

**Comment by William-McGonagle** [comment]
I'm not really sure what the problem is with code duplication. I know that SonarQube is getting pissed at us about it, but it doesn't really seem like that big of a problem. It's really just a meaningless metric (in my opinion).

**Comment by NikitaLejnev** [comment]
@William-McGonagle Please take a look at this article
https://linearb.io/blog/code-duplication/

**Comment by William-McGonagle** [comment]
I just read through the article and I feel like it is important to remove code duplications when it comes to repeating functions, but there are many cases (especially with testing suites) where boilerplate code is somewhat unavoidable. And, there is the pitfall of occasionally trying to get rid of the boilerplate, and that makes the code even less understandable. 

I'm going to look into getting duplicate detection working for [eaf-linter](https://github.com/fairfield-programming/eaf-linter) as it's going to be our new testing, linting, prettying, etc system.

**Comment by NikitaLejnev** [comment]
@William-McGonagle Roger that. If you need help with eaf-linter, I am at your service
