### ISSUE TITLE
Disable SonarQube suggesting for-in loops instead of for-loops

### ISSUE THREAD

**Issue by NikitaLejnev** [fairfield-programming/backend-server#90]
## Idea
For-in loops are more suited for object iteration, not array iteration. For-in loops are slower.
https://stackoverflow.com/questions/242841/javascript-for-in-vs-for

**Comment by William-McGonagle** [comment]
@NikitaLejnev @NeilChaudhari 

Since we three are the top contributors in terms of commits, what would you say about getting rid of SonarQube? I've been analyzing the number of commits and code growth, and we seem to be slowing down noticeably since we added SonarQube.  Let me know down below.

**Comment by NikitaLejnev** [comment]
@NikitaLejnev I agree, would love to see it gone.

**Comment by William-McGonagle** [comment]
Ok- SonarQube is gone! 🎉
